export const data = {
    icons: [
      {
        
        key : 1,
        name : "Phone",
        icon : "faAngry",
        label : "Phone ",
        ref : "refLink",
        onClick : "Function",
        labelClass : "buttonLabel",
        active : "active",
        visible : "visible",
        iconClass : "fas fa-phone",
        page : "/home",
        href:"tel:602-816-1523"
    },
    {
      "key" : 2,
      "name" : "three",
      "icon" : "faAngry",
      "label" : "Message ",
      "ref" : "refLink",
      "onClick" : "Function",
      "labelClass" : "buttonLabel",
      "active" : "active",
      "visible" : "visible",
      "iconClass" : "fas fa-comments",
      page : "/home",
      href:"sms:602-816-1523"
    },  {
      "key" : 3,
      "name" : "three",
      "icon" : "faAngry",
      "label" : "Mail ",
      "ref" : "refLink",
      "onClick" : "Function",
      "labelClass" : "buttonLabel",
      "active" : "active",
      "visible" : "visible",
      "iconClass" : "fa-solid fa-envelope",
      page : "/home",
      href:"mailto:brycengabaldon@gmail.com"
    },      
    {
        key : 4,
        name : "Home",
        icon : "",
        label : "Home ",
        ref : "refLink",
        onClick : "Function",
        labelClass : "buttonLabel1",
        active : "active",
        visible : "visible",
        iconClass : "fa-solid fa-home",
        page : "/home",
        href:""
    },
    {
        
      key : 4,
    name : "five",
    icon : "faAngry",
    label : "Github ",
    ref : "tel:602-816-1523",
    onClick : "Function",
    labelClass : "buttonLabel",
    active : "active",
    visible : "visible",
    iconClass : "fab fa-github",
    page : "/Github",
    href:""
    },
    {
      key : 5,
    name : "six",
    icon : "faAngry",
    label : "Discord ",
    ref : "refLink",
    onClick : "Function",
    labelClass : "buttonLabel",
    active : "active",
    visible : "visible",
    iconClass : "fab fa-discord",
    page : "/Discord",
    href:""
    
  },       {
    key : 5,
  name : "six",
  icon : "faAngry",
  label : "LinkedIn ",
  ref : "refLink",
  onClick : "Function",
  labelClass : "buttonLabel",
  active : "active",
  visible : "visible",
  iconClass : "fa-brands fa-linkedin-in",
  page : "/home",
  href:'https://www.linkedin.com/in/brycen-gabaldon-86aa14253/'
  
},       { key : 7,
  name : "eight",
  icon : "faAngry",
  label : "Lotus ",
  ref : "refLink",
  onClick : "Function",
  labelClass : "buttonLabel",
  active : "active",
  visible : "visible",
  iconClass : "GiLotus",
  iconPass : "GiLotus",
  page: "/Jobber",
  href:""
  },
  {
    key : 8,
    name : "two",
    icon : "faAngry",
    label : "Instagram ",
    ref : "refLink",
    onClick : "Function",
    labelClass : "buttonLabel",
    active : "active",
    visible : "visible",
    iconClass : "fa-brands fa-instagram",
    page : "/Instagram",
    href:""
  
  }, 
  {
    key : 8,
    name : "two",
    icon : "faAngry",
    label : "Youtube ",
    ref : "refLink",
    onClick : "Function",
    labelClass : "buttonLabel",
    active : "active",
    visible : "visible",
    iconClass : "fab fa-youtube",
    page : "/Youtube",
    href:""
  
  }, 
    {    key : 3,
      name : "four",
      icon : "faAngry",
      label : "Planner ",
      ref : "refLink",
      onClick : "Function",
      labelClass : "buttonLabel",
      active : "active",
      visible : "visible",
      iconClass : "fa-solid fa-list",
      page : "/Planner",
      href:""
      },    {    key : 3,
        name : "four",
        icon : "faAngry",
        label : "Resume ",
        ref : "refLink",
        onClick : "Function",
        labelClass : "buttonLabel",
        active : "active",
        visible : "visible",
        iconClass : "fas fa-file",
        page : "/Resume",
        href:""
        },
    {    key : 9,
      name : "four",
      icon : "faAngry",
      label : "Images ",
      ref : "refLink",
      onClick : "Function",
      labelClass : "buttonLabel ",
      active : "active",
      visible : "visible",
      iconClass : "fa-solid fa-icons",
      page : "/Photos",
      href:""
      },
      { key : 7,
        name : "eight",
        icon : "faAngry",
        label : "Lotus ",
        ref : "refLink",
        onClick : "Function",
        labelClass : "buttonLabel",
        active : "active",
        visible : "visible",
        iconClass : "",
        page: "/Home",
        href:""
        },
          {
            "key" :11,
            "name" : "eleven",
            "icon" : "faAngry",
            "label" : "yes?!",
            "ref" : "refLink",
            "onClick" : "Function",
            "labelClass" : "buttonLabel",
            "active" : "active",
            "visible" : "visible",
            iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50",
            click : "FB",
            href:""
},
            {    key : 12,
              name : "twelve",
              icon : "faAngry",
              label : "yes?!",
              ref : "refLink",
              onClick : "Function",
              labelClass : "buttonLabel",
              active : "active",
              visible : "visible",
              iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50",
              click : "FB",
              href:""

              },
              {
                
                key : 13,
              name : "thirteen",
              icon : "faAngry",
              label : "Phone",
              ref : "tel:602-816-1523",
              onClick : "Function",
              labelClass : "buttonLabel",
              active : "active",
              visible : "visible",
              iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50",
              click : "FB",
              href:""

            
              },
              {
                key : 14,
              name : "fourteen",
              icon : "faAngry",
              label : "no?!",
              ref : "refLink",
              onClick : "Function",
              labelClass : "buttonLabel",
              active : "active",
              visible : "visible",
              iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button",
              click : "FB",
              href:""

              
            }, 
            {
              "key" : 15,
              "name" : "fifteen",
              "icon" : "faAngry",
              "label" : "yes?!",
              "ref" : "refLink",
              "onClick" : "Function",
              "labelClass" : "buttonLabel",
              "active" : "active",
              "visible" : "visible",
              iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50",
              click : "FB",
              href:""
},
              {    key : 8,
                name : "messages",
                icon : "faAngry",
                label : "yes?!",
                ref : "refLink",
                onClick : "Function",
                labelClass : "buttonLabel",
                active : "active",
                visible : "visible",
                iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50",
                click : "FB",
                href:""

                }
  ]
  }   