export const data = {
  icons: [
    {
      key: 1,
      name: "Phone",
      icon: "faAngry",
      label: "Call ",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass: "fas fa-phone drop-shadow-lg",
      page: "/home",
      href: "tel:602-816-1523",
    },
    {
      key: 2,
      name: "three",
      icon: "faAngry",
      label: "Message ",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass: "fas fa-comments drop-shadow-lg",
      page: "/home",
      href: "sms:602-816-1523",
    },
    {
      key: 3,
      name: "three",
      icon: "faAngry",
      label: "E-Mail ",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass: "fa-solid fa-envelope drop-shadow-lg",
      page: "/home",
      href: "mailto:brycengabaldon@gmail.com",
    },
    {
      key: 4,
      name: "Home",
      icon: "",
      label: "Profile ",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel1",
      active: "active",
      visible: "visible",
      iconClass: "drop-shadow-lg",
      page: "/profile",
      href: "",
 
      iconPass: true
     
    },              {
      key: 3,
      name: "four",
      icon: "faAngry",
      label: "Resume ",
      ref: "refLink",
      onClick: "Function",
      labelClass: " buttonLabel ",
      active: "active",
      visible: "visible",
      iconClass: " fas fa-file drop-shadow-lg ",
      page: "/Resume",
      href: "",
    },
    
    
    {
      key: 5,
      name: "six",
      icon: "faAngry",
      label: "Discord ",
      ref: "refLink",
      onClick: "Function",
      labelClass: " buttonLabel ",
      active: "active",
      visible: "visible",
      iconClass: "fab fa-discord drop-shadow-lg",
      page: "/Discord",
      href: "",
    },
    
    {
      key: 4,
      name: "five",
      icon: "faAngry",
      label: "Github ",
      ref: "tel:602-816-1523",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass: "fab fa-github drop-shadow-lg",
      page: "/Github",
      href: "",
    },



    {
      key: 5,
      name: "six",
      icon: "faAngry",
      label: "LinkedIn ",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass: "fa-brands fa-linkedin-in drop-shadow-lg",
      page: "/home",
      href: "https://www.linkedin.com/in/brycen-gabaldon-86aa14253/",
    },
    {
      key: 8,
      name: "two",
      icon: "faAngry",
      label: "Instagram ",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass: "fa-brands fa-instagram drop-shadow-lg",
      page: "/Instagram",
      settings:"/InstagramSettings",
      href: "",
    },
    {
      key: 8,
      name: "two",
      icon: "faAngry",
      label: "Youtube ",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass: "fab fa-youtube drop-shadow-lg",
      page: "/Youtube",
      href: "",
    },
    {
      key: 3,
      name: "four",
      icon: "faAngry",
      label: "Planner ",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass: "fa-solid fa-list drop-shadow-lg",
      page: "/Planner",
      href: "",
    },

    {
      key: 9,
      name: "four",
      icon: "faAngry",
      label: "Images ",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel ",
      active: "active",
      visible: "visible",
      iconClass: "fa-solid fa-icons drop-shadow-lg",
      page: "/Photos",
      href: "",
    },
    {
      key: 7,
      name: "eight",
      icon: "faAngry",
      label: "Lotus ",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass: "drop-shadow-lg ",
 
      page: "/Jobber",
      href: "",
    },
    
    {
      key: 7,
      name: "eight",
      icon: "faAngry",
      label: "BubblePop ",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass: "fa-solid fa-volleyball drop-shadow-lg",
      page: "/climber",
      href: "",
    },
    {
      key: 11,
      name: "eleven",
      icon: "faAngry",
      label: "LaRistra ",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      page: "/laristra",
      iconClass:
        " drop-shadow-lg ",
      click: "FB",
      href: "",
    },
    {
      key: 12,
      name: "twelve",
      icon: "faAngry",
      label: "yes?!",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass:
        "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50",
      click: "FB",
      href: "",
    },
    {
      key: 13,
      name: "thirteen",
      icon: "faAngry",
      label: "Phone",
      ref: "tel:602-816-1523",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass:
        "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50",
      click: "FB",
      href: "",
    },
    {
      key: 14,
      name: "fourteen",
      icon: "faAngry",
      label: "no?!",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass:
        "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button",
      click: "FB",
      href: "",
    },
    {
      key: 15,
      name: "fifteen",
      icon: "faAngry",
      label: "yes?!",
      ref: "refLink",
      onClick: "Function",
      labelClass: "buttonLabel",
      active: "active",
      visible: "visible",
      iconClass:
        "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50",
      click: "FB",
      href: "",
    },
  ],
};
