
export const data = {
  icons: [
    {
      
    key : 1,
  name : "one",
  icon : "faAngry",
  label : "one",
  ref : "tel:602-816-1523",
  onClick : "Function",
  labelClass : "buttonLabel",
  active : "active",
  visible : "visible",
  iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button fas fa-phone-alt",
  style : { "background": "linear-gradient(rgb(0, 47, 255), rgb(255, 255, 255))"}

  },
  {
    key : 2,
  name : "two",
  icon : "faAngry",
  label : "two",
  ref : "refLink",
  onClick : "Function",
  labelClass : "buttonLabel",
  active : "active",
  visible : "visible",
  iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button  Small fas fa-envelope",
  style : { "background": "linear-gradient(rgb(155, 236, 0), rgba(0, 50, 0, 0.219))", "color": "white"}
}, 
{
  "key" : 3,
  "name" : "three",
  "icon" : "faAngry",
  "label" : "yes?!",
  "ref" : "refLink",
  "onClick" : "Function",
  "labelClass" : "buttonLabel",
  "active" : "active",
  "visible" : "visible",
  iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button  Small fas fa-comments",
  style : { "background": "linear-gradient(rgb(0, 255, 81), rgb(251, 248, 227))", "color": "green"}
},

  {    key : 4,
    name : "four",
    icon : "faAngry",
    label : "yes?!",
    ref : "refLink",
    onClick : "Function",
    labelClass : "buttonLabel",
    active : "active",
    visible : "visible",
    iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button Small fas fa-file",
    style : { "background": "linear-gradient(rgb(255, 153, 0), rgb(27, 155, 123))"}
    },
    {
      
      key : 5,
    name : "five",
    icon : "faAngry",
    label : "Phone",
    ref : "tel:602-816-1523",
    onClick : "Function",
    labelClass : "buttonLabel",
    active : "active",
    visible : "visible",
    iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button",
  style : { "background": "linear-gradient(rgb(255, 148, 127), rgb(27, 55, 155))"}
  
    },
    {
      key : 6,
    name : "six",
    icon : "faAngry",
    label : "no?!",
    ref : "refLink",
    onClick : "Function",
    labelClass : "buttonLabel",
    active : "active",
    visible : "visible",
    iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button  Small",
    style : { "background": "linear-gradient(rgb(127, 144, 255), rgb(69, 160, 96))"}
    
  }, 
  {
    "key" : 7,
    "name" : "seven",
    "icon" : "faAngry",
    "label" : "yes?!",
    "ref" : "refLink",
    "onClick" : "Function",
    "labelClass" : "buttonLabel",
    "active" : "active",
    "visible" : "visible",
    iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button  Small",
    style : { "background": "linear-gradient(rgb(131, 147, 86), rgb(140, 140, 140))"}},
    {    key : 8,
      name : "eight",
      icon : "faAngry",
      label : "yes?!",
      ref : "refLink",
      onClick : "Function",
      labelClass : "buttonLabel",
      active : "active",
      visible : "visible",
      iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button Small",
      style : { "background": "linear-gradient(rgb(255, 255, 255), rgb(90, 90, 90))"}
      },
      {
            key : 9,
          name : "nine",
          icon : "faAngry",
          label : "nine",
          ref : "tel:602-816-1523",
          onClick : "Function",
          labelClass : "buttonLabel",
          active : "active",
          visible : "visible",
          iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button",
  style : { "background": "linear-gradient(rgb(0, 255, 81), rgb(251, 248, 227))"}
        
          },
          {
            key : 10,
          name : "ten",
          icon : "faAngry",
          label : "ten",
          ref : "refLink",
          onClick : "Function",
          labelClass : "buttonLabel",
          active : "active",
          visible : "visible",
          iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button  Small",
          style : { "background": "linear-gradient(rgb(0, 255, 81), rgb(251, 248, 227))"}
          
        }, 
        {
          "key" :11,
          "name" : "eleven",
          "icon" : "faAngry",
          "label" : "yes?!",
          "ref" : "refLink",
          "onClick" : "Function",
          "labelClass" : "buttonLabel",
          "active" : "active",
          "visible" : "visible",
          iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button  Small",
          style : { "background": "linear-gradient(rgb(0, 255, 81), rgb(251, 248, 227))"}},
          {    key : 12,
            name : "twelve",
            icon : "faAngry",
            label : "yes?!",
            ref : "refLink",
            onClick : "Function",
            labelClass : "buttonLabel",
            active : "active",
            visible : "visible",
            iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button Small",
            style : { "background": "linear-gradient(rgb(0, 255, 81), rgb(251, 248, 227))"}
            },
            {
              
              key : 13,
            name : "thirteen",
            icon : "faAngry",
            label : "Phone",
            ref : "tel:602-816-1523",
            onClick : "Function",
            labelClass : "buttonLabel",
            active : "active",
            visible : "visible",
            iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button",
            style : { "background": "linear-gradient(rgb(0, 255, 81), rgb(251, 248, 227))"}
          
            },
            {
              key : 14,
            name : "fourteen",
            icon : "faAngry",
            label : "no?!",
            ref : "refLink",
            onClick : "Function",
            labelClass : "buttonLabel",
            active : "active",
            visible : "visible",
            iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button  Small",
            style : { "background": "linear-gradient(rgb(0, 255, 81), rgb(251, 248, 227))"}
            
          }, 
          {
            "key" : 15,
            "name" : "fifteen",
            "icon" : "faAngry",
            "label" : "yes?!",
            "ref" : "refLink",
            "onClick" : "Function",
            "labelClass" : "buttonLabel",
            "active" : "active",
            "visible" : "visible",
            iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button  Small",
            style : { "background": "linear-gradient(rgb(0, 255, 81), rgb(251, 248, 227))"}},
            {    key : 8,
              name : "messages",
              icon : "faAngry",
              label : "yes?!",
              ref : "refLink",
              onClick : "Function",
              labelClass : "buttonLabel",
              active : "active",
              visible : "visible",
              iconClass : "Icons1 aspect-w-1 aspect-h-1 shadow-lg  hover:shadow-gray-500/50 Button Small",
              style : { "background": "linear-gradient(rgb(255, 153, 0), rgb(251, 248, 227))"}
              }
]
}