export const data2 = {
  recipes: [
    {
      Name: "",
      liquor: "",
      liquor1: "",
      liquor2: "",
      liquor3: "",
      liquor4: "",
      mixer1: "",
      mixer2: "",
      mixer3: "",
      mixer4: "",
      prep: "",
      glass: "",
      garnish: "",
    },
    {
      Name: "Portland Tonic",

      liquor1: "1oz White Port",
      liquor2: "1 1/2 Tanqueray",
      liquor3: "",
      liquor4: "",
      mixer1: "1/4 Oleo",
      mixer2: "1/4 Lemon",
      mixer3: "",
      mixer4: "",
      prep: "Shake - Dirty Dump",
      glass: "Wine Glass",
      garnish: "Peppercorn + Lemon",
    },
    {
      Name: "Up All Night",

      liquor1: "1 1/2 Vodka",
      liquor2: "3/4 Orangeat",
      liquor3: "1/2 Cafe Mocha",
      liquor4: "1/2 Mr Blake",
      mixer1: "1oz Cold Brew",
      mixer2: "",
      mixer3: "",
      mixer4: "",
      prep: "Shake - No Strain",
      glass: "Coupe",
      garnish: "3 Coffee Beans",
    },
    {
      Name: "Kings Cup",

      liquor1: "1 1/2 Honeydew",
      liquor2: "1 1/2 Brandy",
      liquor3: "1/2 Ming River",
      liquor4: "1/4 Orangeat",
      mixer1: "Ango Bitters",
      mixer2: "3/4 Sesame Syrup",
      mixer3: "1 1/2 Grapefruit",
      mixer4: "1/2 Lime",
      prep: "",
      glass: "Tiki Mug",
      garnish: "Leaves + Orchid",
    },
    {
      Name: "The Rebel Genius",

      liquor1: "1 1/2 Mezcal",
      liquor2: "1/2 Orangeat",
      liquor3: "3/4 Triple Sec",
      liquor4: "1/2 Montenegro Float",
      mixer1: "3/4 Lime",
      mixer2: "",
      mixer3: "",
      mixer4: "",
      prep: "Shake",
      glass: "Rocks w/ Big Cube",
      garnish: "Dehydrated Lime + Orchid",
    },
    {
      Name: "Tennesee Buck",

      liquor1: "2 Gentlemans Jack",
      liquor2: "",
      liquor3: "",
      liquor4: "",
      mixer1: "3/4 lemon",
      mixer2: "1/2 Honey Syrup",
      mixer3: "2 Muddled Strawberries",
      mixer4: "Top with ginger beer",
      prep: "Shake",
      glass: "Collins w/ Ice",
      garnish: "Lemon Peel + Ango Float",
    },
    {
      Name: "Sweet Potato Old Fashioned",

      liquor1: "1/2 Black Walnut",
      liquor2: "2 Rye",
      liquor3: "",
      liquor4: "",
      mixer1: "Walnut Bitters",
      mixer2: "3/4 Sweet Potato",
      mixer3: "",
      mixer4: "",
      prep: "Stir",
      glass: "Rocks w/ Big Cube",
      garnish: "Nutmeg",
    },
    {
      Name: "The French Impression",

      liquor1: "2 Vodka+",
      liquor2: "1/2 Razz",
      liquor3: "",
      liquor4: "",
      mixer1: "1/4 Lemon",
      mixer2: "1 1/2 Pineapple",
      mixer3: "",
      mixer4: "",
      prep: "Shake",
      glass: "Coupe",
      garnish: "Thyme",
    },
    {
      Name: "Prickly Pear Martinez",

      liquor1: "1/2 Sweet Vermouth",
      liquor2: "1/4 Marachino",
      liquor3: "1 1/2 Gin",
      liquor4: "",
      mixer1: "1/4 Lemon",
      mixer2: "1/4 Prickly Pear",
      mixer3: "",
      mixer4: "",
      prep: "Shake",
      glass: "Rocks w/ Ice",
      garnish: "Lemon Twist",
    },
    {
      Name: "Lemon Drop",

      liquor1: "2 Hendricks",
      liquor2: "1/4 Limoncello",
      liquor3: "1/4 Cointreau",
      liquor4: "",
      mixer1: "3/4 Lemon",
      mixer2: "1/2 Simple",
      mixer3: "",
      mixer4: "",
      prep: "Shake",
      glass: "Coupe",
      garnish: "None",
    },
    {
      Name: "Tea And Smoke",

      liquor1: "1 1/2 Zacapa",
      liquor2: "1/2 Yellow Chatreuse",
      liquor3: "1 1/2 Amaro Blend",
      liquor4: "",
      mixer1: "",
      mixer2: "",
      mixer3: "",
      mixer4: "",
      prep: "Stir",
      glass: "Nick & Nora",
      garnish: "Bergomot Flavor",
    },
    {
      Name: "Spice and Everything Nice",

      liquor1: "1 Well Tequila",
      liquor2: "1/2 Mezcal",
      liquor3: "1/4 Jalapeno Tequila",
      liquor4: "",
      mixer1: "1 Grapefruit",
      mixer2: "1/4 Lime",
      mixer3: "1/2 Cinnamon Simple",
      mixer4: "",
      prep: "Shake",
      glass: "Tulip W/Ice",
      garnish: "Jala Slices",
    },
    {
      Name: "Paradox of Choice",

      liquor1: "2 Reposado",
      liquor2: "1/2 benedictine",
      liquor3: "",
      liquor4: "",
      mixer1: "1/4 simple",
      mixer2: "3/4 lime",
      mixer3: "",
      mixer4: "",
      prep: "Shake",
      glass: "Coupe",
      garnish: "Red Wine Float",
    }]}